image: elivz/php

variables:
  LIVE_SSH_USER: REPLACE_ME
  LIVE_DOMAIN: REPLACE_ME
  LIVE_ROOT: /var/www/public
  STAGING_SSH_USER: REPLACE_ME
  STAGING_DOMAIN: REPLACE_ME
  STAGING_ROOT: /var/www/staging_html

cache:
  paths:
    - node_modules
    - dist/vendor

before_script:
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - composer install --no-interaction --no-dev --no-scripts --prefer-dist --no-progress
  - yarn --non-interactive --silent --frozen-lockfile
  - yarn build

stage_deploy:
  stage: deploy
  only:
    - develop
  script:
    - rsync -chaz --stats --delete --exclude 'storage/*' --exclude 'public/media' --exclude '.env' ./dist/* ${STAGING_SSH_USER}@${STAGING_DOMAIN}:${STAGING_ROOT}
    - ssh ${STAGING_SSH_USER}@${STAGING_DOMAIN} "${STAGING_ROOT}/craft migrate/all;${STAGING_ROOT}/craft cache/flush-all"

live_deploy:
  stage: deploy
  only:
    - master
  script:
    - rsync -chaz --stats --delete --exclude 'storage/*' --exclude 'public/media' --exclude '.env' ./dist/* ${LIVE_SSH_USER}@${LIVE_DOMAIN}:${LIVE_ROOT}
    - ssh ${LIVE_SSH_USER}@${LIVE_DOMAIN} "${LIVE_ROOT}/craft migrate/all;${LIVE_ROOT}/craft cache/flush-all"
