version: '3'

services:
  web:
    image: elivz/php
    ports:
      - '8080:80'
      - '3000:3000'
    volumes:
      - ..:/var/www:delegated
      - node_modules:/var/www/node_modules
      - vendor:/var/www/dist/vendor
    links:
      - db
      - redis
    environment:
      # Don't change these
      ENVIRONMENT:
      BASE_URL:
      BASE_PATH:
      PUBLIC_FOLDER: /dist${PUBLIC_FOLDER}
      SECURITY_KEY:
      DB_HOST:
      DB_NAME:
      DB_USER:
      DB_PASS:
      DB_PORT:
      REDIS_HOST:
      REDIS_PORT:
      IP:

  db:
    image: mariadb
    ports:
      - '4306:3306'
    volumes:
      - data-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: 123
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: password

  redis:
    image: redis:4.0-alpine

volumes:
  data-volume:
  node_modules:
  vendor:
